### ISSUE TITLE
EVERYTHING IS BLUE - Cartoon shader 

### ISSUE THREAD

**Issue by biscotteman** [nealith/SI_TP2#2]
Le chargement du shader Cartoon donne un écran bleu.
Si on commente le chargement du shader dans le example_castle_scene.xml, ça refonctionne.
Si on remplace le code actuel du shader Cartoon par le code d'un autre shader (ex Phong), ça refonctionne.

**Comment by fonspa** [comment]
En effet, pareil chez moi. Je suis obligé de commenter le chargement du shader dans le fichier .xml pour loader correctement la scène.

**Comment by biscotteman** [comment]
Ce qui est bizarre c'est qu'il fait tout bugger même sans qu'on l'applique sur un objet, c'est pas super normal.

**Comment by romainringenbach** [comment]
si c'est normal, les shaders sont testé au chargement, vous avez pas un alerte ? 
je vérifie de mon côté le code, ça vient peut être aussi de votre modification ?, je vérifie et je vous redis si vous devez commencer à regarder du côté de votre modif

**Comment by romainringenbach** [comment]
Je viens de relancer, de mon côté j'ai aucun problème, en rentrant manuellement le shader dans le xml, dans un des objets ça marche, je pensais que c'était parce que le nombre de nbtex n'était pas bon mais non, ça marche toujours pas, ça vient peut être de votre chargeur, je vais regarder (comme ça je verrai votre code x) )

**Comment by romainringenbach** [comment]
Yo, j'ai remis le code à la normal, relancer, blue screen, en appuyant sur p, ça charge bien le cartoon ^^, je vais regarder plus loin

**Comment by biscotteman** [comment]
Je viens de clone chez moi, blue screen de base, si j'appuie sur P je vois la skybox mais rien d'autre

**Comment by romainringenbach** [comment]
ah, moi j'ai tout en cartoon x), quel navigateur ?
j'ai pas push la correction pour le xml, faut juste que tu repasse nbtex à 1

**Comment by fonspa** [comment]
Pareil, je vois que la skybox avec le shader toon, même en repassant nbtext à 1. Firefox comme navigateur.

**Comment by biscotteman** [comment]
Firefox. C'est fait

**Comment by romainringenbach** [comment]
bref chez moi ça marche quand je met en dur ou que j'appuie sur p, quand vous regarder dans les consoles, ça vous met quoi ?

Sinon, pour l'instant ma seul theorie c'est que webgl n'aime pas avoir des shaders inutilisé à l'inialisation, je vais essayer de tester ça

**Comment by fonspa** [comment]
```
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
atomicGL2Object3d.js:137:9
Error: WebGL warning: drawElements: no VBO bound to enabled vertex attrib index 3u!
```

C'est surtout la deuxième erreur qui est spécifique au load du shaderToon

**Comment by biscotteman** [comment]
Je confirme, en utilisant le shader à l'initialisation, il n'affiche plus le carré bleu

**Comment by biscotteman** [comment]
Par contre j'ai toujours que la skybox quand j'appuie sur P

**Comment by romainringenbach** [comment]
correctif du shader toon en ligne, dites moi ce que ça donne :)

**Comment by biscotteman** [comment]
Toujours pareil pour moi...

**Comment by romainringenbach** [comment]
étrange, print moi tes erreurs

**Comment by biscotteman** [comment]
```
Error: WebGL warning: vertexAttribPointer: -1 is not a valid `index`. This value probably comes from a getAttribLocation() call, where this return value -1 means that the passed name didn't correspond to an active attribute in the specified program.
atomicGL2Object3d.js:137:9
Error: WebGL warning: drawElements: no VBO bound to enabled vertex attrib index 3u!
```
Il me met ça plusieurs fois

**Comment by biscotteman** [comment]
Et ça marche chez toi ?

**Comment by romainringenbach** [comment]
je suis de retour, je regarde ton code maintenant,

tu peux me dire qu'elle version de firefox tu utilises ?

essaie la version développeur et fait moi un retour

**Comment by biscotteman** [comment]
57.0, donc même version qu'à l'école

**Comment by romainringenbach** [comment]
d'accord, la dev est encore en version 56, test là pour voir, de mon côté j'ai trouvé un truc intéressant, je fais une modif et je push, tu me redira :)

**Comment by romainringenbach** [comment]
go discord

**Comment by fonspa** [comment]
Je viens de pull ton dernier commit. Testé et ça foire toujours :'(

**Comment by romainringenbach** [comment]
go discord

**Comment by biscotteman** [comment]
Corrigé.
Dans le Vertex, commenter le varying vColor, et la ligne vColor = aVertexColor;
Je comprends pas pourquoi ça marchait chez toi du coup ¯\_(ツ)_/¯

**Comment by romainringenbach** [comment]
mouai, va falloir redemander au prof, en effet ça marche toujours chez moi après les avoir commenter, mais du coup, ça devrait pas fonctionner non plus, parce que dans fragment du déclare l'input varying vColor, donc ... 

En plus ça vient du code du prof, en y regardant le plus près, je me rend compte que vColor sert à rien (du moins semble t-il, de plus je suppose que ça planterai)
