### ISSUE TITLE
Fucking textures

### ISSUE THREAD

**Issue by biscotteman** [nealith/SI_TP2#6]
Always doing shit and render like they don't care if it's ugly

**Comment by fonspa** [comment]
Quelle scène, quelles textures ? Dans quelles circonstances ?
**T'as essayé de passer toutes les textures en PNG ?**

**Comment by fonspa** [comment]
T'as essayé de passer toutes les textures en PNG ?

**Comment by biscotteman** [comment]
Textures en PNG -> Pas de changement
Essai : séparer le .obj en plusieurs objets pour chaque matériau

**Comment by romainringenbach** [comment]
je rajouterai même que le passage par blender puis obj, n'a rien changé
non plus

**Comment by biscotteman** [comment]
https://blender.stackexchange.com/questions/32677/how-to-combine-two-different-textures-into-one

**Comment by romainringenbach** [comment]
Je suis tombé dessus aussi, mais je t'avoue que j'ai pas pris le temps
d'essayer encore

**Comment by biscotteman** [comment]
Chaque objet sera séparé en plusieurs sous-objets. Problème résolu.
